### ISSUE TITLE
Rename the default branch of this repo from `master` to `main`

### ISSUE THREAD

**Issue by rsimha** [ampproject/validator-java#31]
See https://github.com/ampproject/amphtml/issues/32195 for more details

**Comment by nhant01** [comment]
@rsimha @Gregable would you grant me and George the admin rights to this repo? We're seeing very limited in the Settings such as Option. We need the ability to set the default branch to 'main'.

**Comment by rsimha** [comment]
Looks like this will need an accompanying change to the CI config for this repo. Will leave it to @Gregable or @honeybadgerdontcare to further advise.

**Comment by nhant01** [comment]
We switch the default branch from master to main.
